#!/usr/bin/env bash
#This Script is a FizzBuzz condition, it will display fizzbuzz when a number is a multiple of 3 and 5, Fizz when the number is a multiple of 3 and Buzz when the number is a multiple of 5, otherwise it displays the number.
for number in {1..100}
do
    if (( number % 3 == 0 && number % 5 == 0 ))
    then
	    echo "FizzBuzz"
    elif (( number % 3 == 0 ))
    then
	    echo "Fizz"
    elif (( number % 5 == 0 ))
    then
	    echo "Buzz"
    else
	    echo "$number"
    fi
done
