#!/usr/bin/env bash
# Bash script that displays to infinity and beyond

while :                                            
do                                                 
        echo "To infinity and beyond"              
        sleep 2                                    
        trap 'echo "I am invincible!!!"' SIGTERM   
done
